### ISSUE TITLE
Error. Whats the issue here? wrong source code?

### ISSUE THREAD

**Issue by nFeyz** [mopihu/world-boss-helper#7]
[12:20:56.280] [dispatch] [world-boss-helper] handle: error running hook for S_SPAWN_NPC<11>
hook: (anonymous) in world-boss-helper
data: { gameId: 3518437209472033n,
  target: 0n,
  loc:
   Vec3 { x: 116605.1484375, y: 69930.671875, z: 3869.8251953125 },
  w: -1.05231082048955,
  relation: 12,
  templateId: 5011,
  huntingZoneId: 4,
  shapeId: 0,
  walkSpeed: 100,
  runSpeed: 160,
  status: 0,
  mode: 0,
  remainingEnrageTime: -178773062,
  hpLevel: 5,
  questInfo: 0,
  visible: true,
  villager: false,
  spawnType: 1,
  replaceId: 0n,
  spawnScript: 0,
  replaceDespawnScript: 0,
  aggressive: false,
  owner: 0n,
  occupiedByPartyId: 0n,
  occupiedByPlayerId: 0n,
  bomb: false,
  bySpawnEvent: false,
  bgTeam: 0,
  activeCylinder: 1,
  repairable: true,
  flightInteractionType: 0,
  unkn1: false,
  seats: [],
  parts: [],
  npcName: '유안티 샤먼(고레벨)' }
error: [dispatch] write: failed to generate S_SPAWN_DROPITEM<6>:
Error: version 6 of message (name: "S_SPAWN_DROPITEM", code: 36948) is outdated and cannot be used anymore
    at spawnItem (Z:\Games\TeraProxyCaali\mods\world-boss-helper-master\index.js:126:9)
    at Object.callback (Z:\Games\TeraProxyCaali\mods\world-boss-helper-master\index.js:73:9)

**Comment by DeathDefying** [comment]
@nFeyz CHANGE mod.send('S_SPAWN_DROPITEM', 6, to mod.send('S_SPAWN_DROPITEM', 7, 
and disable autoupdate and it will work
